package com.wenyanwen123.learning.commons.domain.learningdb;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_name
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_details
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private String goodsDetails;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_stock
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer goodsStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.total_sales
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer totalSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.create_time
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.create_date
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.update_time
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.update_date
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.is_on_sale
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Boolean isOnSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.is_delete
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_id
     *
     * @return the value of t_goods.goods_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_id
     *
     * @param goodsId the value for t_goods.goods_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_name
     *
     * @return the value of t_goods.goods_name
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_name
     *
     * @param goodsName the value for t_goods.goods_name
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_details
     *
     * @return the value of t_goods.goods_details
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public String getGoodsDetails() {
        return goodsDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_details
     *
     * @param goodsDetails the value for t_goods.goods_details
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setGoodsDetails(String goodsDetails) {
        this.goodsDetails = goodsDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_stock
     *
     * @return the value of t_goods.goods_stock
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getGoodsStock() {
        return goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_stock
     *
     * @param goodsStock the value for t_goods.goods_stock
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setGoodsStock(Integer goodsStock) {
        this.goodsStock = goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.total_sales
     *
     * @return the value of t_goods.total_sales
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getTotalSales() {
        return totalSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.total_sales
     *
     * @param totalSales the value for t_goods.total_sales
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setTotalSales(Integer totalSales) {
        this.totalSales = totalSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_time
     *
     * @return the value of t_goods.create_time
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_time
     *
     * @param createTime the value for t_goods.create_time
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_date
     *
     * @return the value of t_goods.create_date
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_date
     *
     * @param createDate the value for t_goods.create_date
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setCreateDate(Integer createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.update_time
     *
     * @return the value of t_goods.update_time
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.update_time
     *
     * @param updateTime the value for t_goods.update_time
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.update_date
     *
     * @return the value of t_goods.update_date
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.update_date
     *
     * @param updateDate the value for t_goods.update_date
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setUpdateDate(Integer updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.is_on_sale
     *
     * @return the value of t_goods.is_on_sale
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Boolean getIsOnSale() {
        return isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.is_on_sale
     *
     * @param isOnSale the value for t_goods.is_on_sale
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setIsOnSale(Boolean isOnSale) {
        this.isOnSale = isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.is_delete
     *
     * @return the value of t_goods.is_delete
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.is_delete
     *
     * @param isDelete the value for t_goods.is_delete
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}