package com.wenyanwen123.learning.commons.domain.learningdb;

import java.util.Date;

public class RecordOfGoodsSold {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.record_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.goods_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.user_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.user_name
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.current_stock
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer currentStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.purchase_result
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Boolean purchaseResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.remark
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.create_time
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.create_date
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Integer createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record_of_goods_sold.is_delete
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.record_id
     *
     * @return the value of t_record_of_goods_sold.record_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.record_id
     *
     * @param recordId the value for t_record_of_goods_sold.record_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.goods_id
     *
     * @return the value of t_record_of_goods_sold.goods_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.goods_id
     *
     * @param goodsId the value for t_record_of_goods_sold.goods_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.user_id
     *
     * @return the value of t_record_of_goods_sold.user_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.user_id
     *
     * @param userId the value for t_record_of_goods_sold.user_id
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.user_name
     *
     * @return the value of t_record_of_goods_sold.user_name
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.user_name
     *
     * @param userName the value for t_record_of_goods_sold.user_name
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.current_stock
     *
     * @return the value of t_record_of_goods_sold.current_stock
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getCurrentStock() {
        return currentStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.current_stock
     *
     * @param currentStock the value for t_record_of_goods_sold.current_stock
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setCurrentStock(Integer currentStock) {
        this.currentStock = currentStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.purchase_result
     *
     * @return the value of t_record_of_goods_sold.purchase_result
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Boolean getPurchaseResult() {
        return purchaseResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.purchase_result
     *
     * @param purchaseResult the value for t_record_of_goods_sold.purchase_result
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setPurchaseResult(Boolean purchaseResult) {
        this.purchaseResult = purchaseResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.remark
     *
     * @return the value of t_record_of_goods_sold.remark
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.remark
     *
     * @param remark the value for t_record_of_goods_sold.remark
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.create_time
     *
     * @return the value of t_record_of_goods_sold.create_time
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.create_time
     *
     * @param createTime the value for t_record_of_goods_sold.create_time
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.create_date
     *
     * @return the value of t_record_of_goods_sold.create_date
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Integer getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.create_date
     *
     * @param createDate the value for t_record_of_goods_sold.create_date
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setCreateDate(Integer createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record_of_goods_sold.is_delete
     *
     * @return the value of t_record_of_goods_sold.is_delete
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record_of_goods_sold.is_delete
     *
     * @param isDelete the value for t_record_of_goods_sold.is_delete
     *
     * @mbg.generated Mon Feb 10 17:48:54 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}